-- equip-seed-mic-2026-08.sql — i 30 microfoni più usati nei rider, per il campo «Modello reale».
-- Ogni valore porta la CITAZIONE del documento da cui è stato letto (doc, pagina, frase):
-- è quella che fa comparire «dati verificati» nell'app, e permette di ricontrollare senza fidarsi.
-- Estratti da PDF ufficiali in MANUALI_PDF/microfoni con tmp/estrai.py, che scarta ogni valore
-- che non compaia nella frase citata. Idempotente (upsert): si può rieseguire.
begin;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-beta87a-guide', 'Shure', 'Beta 87A', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/BETA87A/en-US', 'Shure_BETA87A_Guide.pdf', '6392aba0', 8, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-ksm9-guide', 'Shure', 'KSM9', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/KSM9/en-US', 'Shure_KSM9_Guide.pdf', 'a9103e44', 7, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-sm86-guide', 'Shure', 'SM86', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/SM86/en-US', 'Shure_SM86_Guide.pdf', '7c0618a9', 12, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-beta57a-guide', 'Shure', 'Beta 57A', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/BETA57A/en-US', 'Shure_BETA57A_Guide.pdf', 'bde79126', 7, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-beta56a-guide', 'Shure', 'Beta 56A', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/BETA56A/en-US', 'Shure_BETA56A_Guide.pdf', '9193157e', 8, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-beta98amp-guide', 'Shure', 'Beta 98AMP/C', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/BETA98AMP/en-US', 'Shure_BETA98AMP_Guide.pdf', 'd5252aa3', 8, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-beta98h-guide', 'Shure', 'Beta 98H/C', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/BETA98H/en-US', 'Shure_BETA98H_Guide.pdf', '024b8259', 4, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-ksm137-guide', 'Shure', 'KSM137', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/KSM137/en-US', 'Shure_KSM137_Guide.pdf', '86a4596a', 10, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-beta181-guide', 'Shure', 'Beta 181', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/BETA181/en-US', 'Shure_BETA181_Guide.pdf', 'ea416ca0', 10, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-sm7b-guide', 'Shure', 'SM7B', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/SM7B/en-US', 'Shure_SM7B_Guide.pdf', 'cfda1c5f', 13, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('shure-twinplex-tl45-tl47-guide', 'Shure', 'TwinPlex TL47', 'microfono', 'UserGuide', 'en', 'https://pubs.shure.com/guide/TwinPlex/en-US', 'Shure_TwinPlex_TL45-TL47_Guide.pdf', 'd29f8430', 21, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-e935-spec', 'Sennheiser', 'e 935', 'microfono', 'SpecSheet', 'en', null, 'Sennheiser_e935_Spec.pdf', '338a3f0f', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-e945-spec', 'Sennheiser', 'e 945', 'microfono', 'SpecSheet', 'en', null, 'Sennheiser_e945_Spec.pdf', 'eec05c37', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-e865-spec', 'Sennheiser', 'e 865', 'microfono', 'SpecSheet', 'en', null, 'Sennheiser_e865_Spec.pdf', '8ba9658f', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-e902-spec', 'Sennheiser', 'e 902', 'microfono', 'SpecSheet', 'en', null, 'Sennheiser_e902_Spec.pdf', '436f6c8a', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-e901-spec', 'Sennheiser', 'e 901', 'microfono', 'SpecSheet', 'en', null, 'Sennheiser_e901_Spec.pdf', 'a37ac2d9', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-e614-spec', 'Sennheiser', 'e 614', 'microfono', 'SpecSheet', 'en', null, 'Sennheiser_e614_Spec.pdf', '11b8afd8', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-md441-u-quickguide', 'Sennheiser', 'MD 441-U', 'microfono', 'UserGuide', 'en', null, 'Sennheiser_MD441-U_QuickGuide.pdf', '52d94912', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('sennheiser-mkh416-spec', 'Sennheiser', 'MKH 416-P48 U3', 'microfono', 'SpecSheet', 'en', null, 'Sennheiser_MKH416_Spec.pdf', '220fbf32', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('akg-d112mkii-cutsheet', 'AKG', 'D112 MkII', 'microfono', 'CutSheet', 'en', null, 'AKG_D112MkII_CutSheet.pdf', '4b18c553', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('akg-c451b-cutsheet', 'AKG', 'C451 B', 'microfono', 'CutSheet', 'en', null, 'AKG_C451B_CutSheet.pdf', 'e156bcd1', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('akg-c214-cutsheet', 'AKG', 'C214', 'microfono', 'CutSheet', 'en', null, 'AKG_C214_CutSheet.pdf', '5f773a0c', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('akg-d5s-cutsheet', 'AKG', 'D5', 'microfono', 'CutSheet', 'en', null, 'AKG_D5S_CutSheet.pdf', '380a7ceb', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('akg-d40-cutsheet', 'AKG', 'D40', 'microfono', 'CutSheet', 'en', null, 'AKG_D40_CutSheet.pdf', '437e6356', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('electrovoice-re20-datasheet', 'Electro-Voice', 'RE20', 'microfono', 'UserGuide', 'en', null, 'ElectroVoice_RE20_DataSheet.pdf', '1467df35', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('beyerdynamic-m88tg-datasheet', 'beyerdynamic', 'M 88', 'microfono', 'Datasheet', 'en', null, 'Beyerdynamic_M88TG_Datasheet.pdf', '5b98d699', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('rode-nt5-datasheet', 'RODE', 'NT5', 'microfono', 'Datasheet', 'en', 'https://cdn1.rode.com/nt5_datasheet.pdf', 'Rode_NT5_Datasheet.pdf', '9ed2df53', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('rode-nt1-5thgen-datasheet', 'RODE', 'NT1 5th Generation', 'microfono', 'Datasheet', 'en', null, 'Rode_NT1-5thGen_Datasheet.pdf', '515acaf9', 2, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('se-v7-usermanual', 'sE Electronics', 'V7', 'microfono', 'Manual', 'en', null, 'sE_V7_UserManual.pdf', '57be3812', 20, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, sha256, pages, source_quality)
values ('audix-om5-specsheet', 'Audix', 'OM5', 'microfono', 'SpecSheet', 'en', 'https://audixusa.com/cdn/shop/files/OM5_V3_0516.pdf', 'Audix_OM5_SpecSheet.pdf', null, null, 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, filename=excluded.filename,
  sha256=excluded.sha256, pages=excluded.pages, source_quality=excluded.source_quality;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta87a', 'Shure', 'Beta 87A', 'microfono', 'current', 'shure-beta87a-guide', $eq${"id": "shure-beta87a", "brand": "Shure", "model": "Beta 87A", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 5, "quote": "Type ⏎ Electret Condenser"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 3, "quote": "• Uniform supercardioid pick-up pattern for maximum gain before feedback and superior rejection of off-axis sound"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 6, "quote": "11 to 52 V DC phantom power (1.2 mA)"}, "note": "Condensatore electret: richiede phantom 11-52 V."}, "freqResp_lo_hz": {"value": 50, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 5, "quote": "Frequency Response ⏎ 50 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 5, "quote": "Frequency Response ⏎ 50 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 2.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 5, "quote": "Sensitivity ⏎ -52.5 dBV/Pa(2 mV)[1]"}}, "sensitivity_dbv": {"value": -52.5, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 5, "quote": "-52.5 dBV/Pa(2 mV)[1]"}}, "impedance_ohm": {"value": 150, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 5, "quote": "Output Impedance ⏎ EIA rated at150 Ω(100 Ω actual)"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA87A_Guide", "page": 5, "quote": "Most modern mixers provide phantom power. You must use a balanced microphone cable: XLR-to-XLR or XLR-to-TRS."}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-beta87a', 'shure-beta87a-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-ksm9', 'Shure', 'KSM9', 'microfono', 'current', 'shure-ksm9-guide', $eq${"id": "shure-ksm9", "brand": "Shure", "model": "KSM9", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 6, "quote": "Cartridge Type  Electret Condenser"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 3, "quote": "turing unique, switchable polar patterns and a ⏎ • Dual 3/4\" gold layered, low-mass Mylar®  KSM9HS: Features hypercardioid and subcar-"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 6, "quote": "All specifications measured with a 48 Vdc phantom power supply. The microphone"}, "note": "Doppio diaframma, figura commutabile cardioide/supercardioide."}, "freqResp_lo_hz": {"value": 50, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 6, "quote": "Frequency Response  50 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 6, "quote": "Frequency Response  50 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 2.8, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 6, "quote": "Sensitivity  –51 dBV/Pa[1] (2.8 mV)"}}, "impedance_ohm": {"value": 1000, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 4, "quote": "load impedance of 1000 Ohms. Most modern microphone preamplifiers meet this requirement. Higher"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM9_Guide", "page": 4, "quote": "require the use of a balanced microphone cable: XLR-to-XLR or XLR-to-TRS."}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-ksm9', 'shure-ksm9-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-sm86', 'Shure', 'SM86', 'microfono', 'current', 'shure-sm86-guide', $eq${"id": "shure-sm86", "brand": "Shure", "model": "SM86", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "Transducer Type ⏎ Condenser (electret bias)  VOLTAGE"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 1, "quote": "The Shure SM86 is a unidirectional (cardioid) condenser vocal"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "52 Vdc phantom voltage."}, "note": "Condensatore electret: richiede phantom."}, "freqResp_lo_hz": {"value": 50, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "Frequency Response ⏎ 50 to 18,000 Hz (see Figure 2)  SM86 BLOCK DIAGRAM"}}, "freqResp_hi_hz": {"value": 18000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "Frequency Response ⏎ 50 to 18,000 Hz (see Figure 2)  SM86 BLOCK DIAGRAM"}}, "sensitivity_mvpa": {"value": 3.15, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "Sensitivity (at 1,000 Hz)  FURNISHED ACCESSORIES ⏎ Open Circuit Voltage . . . . . . . . . . . . . . . –50 dBV/Pa (3.15 mV)  Break Resistant Microphone Clip . . . . . . . . . . . . . . . . . . . . . A25D"}}, "sensitivity_dbv": {"value": -50.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 12, "quote": "\u0001\u0002 !\" . . . . . . . . . . . . . . . . . . . . . -50 dBV/Pa (3.15 mV)  \u0001\u0002 !\"#$%&#'() . . . . . . . . . . . . . . . . . . . . . . . A25D"}}, "impedance_ohm": {"value": 600, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "A load impedance of at least 600 Ohms is recommended. The load  pin 2 relative to pin 3 of the output connector. See Figure 4."}}, "maxSPL_db": {"value": 124, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "124 dB (maximum SPL to A-weighted noise level)"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM86_Guide", "page": 2, "quote": "Three–pin (XLR) professional audio"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-sm86', 'shure-sm86-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta57a', 'Shure', 'Beta 57A', 'microfono', 'current', 'shure-beta57a-guide', $eq${"id": "shure-beta57a", "brand": "Shure", "model": "Beta 57A", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 5, "quote": "Type ⏎ Dynamic (moving coil)"}}, "polar": {"value": "supercardioide", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 3, "quote": "studio recording. A tight, supercardioid pattern delivers high gain before feedback, maximum sound isolation, and minimum off-"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 1, "quote": "The Shure supercardioid dynamic microphone, BETA57A, user guide."}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 50, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 5, "quote": "Frequency Response ⏎ 50 to 16,000 Hz"}}, "freqResp_hi_hz": {"value": 16000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 5, "quote": "Frequency Response ⏎ 50 to 16,000 Hz"}}, "sensitivity_dbv": {"value": -51.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 5, "quote": "-51 dBV/Pa (2 .8 mV) [1]"}}, "impedance_ohm": {"value": 290, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 5, "quote": "Output Impedance ⏎ 290 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA57A_Guide", "page": 5, "quote": "Three-pin professional audio (XLR), male, balanced"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-beta57a', 'shure-beta57a-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta56a', 'Shure', 'Beta 56A', 'microfono', 'current', 'shure-beta56a-guide', $eq${"id": "shure-beta56a", "brand": "Shure", "model": "Beta 56A", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 5, "quote": "Type ⏎ Dynamic (moving coil)"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 3, "quote": "tremely uniform supercardioid pattern provides high gain before feedback and excellent rejection of unwanted noise. An inte­"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 1, "quote": "The Shure supercardioid dynamic microphone, BETA56A, user guide."}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 50, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 5, "quote": "Frequency Response ⏎ 50 to 16,000 Hz"}}, "freqResp_hi_hz": {"value": 16000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 5, "quote": "Frequency Response ⏎ 50 to 16,000 Hz"}}, "sensitivity_mvpa": {"value": 2.8, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 6, "quote": "Sensitivity ⏎ ­51 dBV/Pa(2.8 mV) [1]"}}, "impedance_ohm": {"value": 290, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 6, "quote": "Output Impedance ⏎ 290 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA56A_Guide", "page": 3, "quote": "grated, locking stand adapter, with XLR connector, simplifies mounting and adjustments."}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-beta56a', 'shure-beta56a-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta98ampc', 'Shure', 'Beta 98AMP/C', 'microfono', 'current', 'shure-beta98amp-guide', $eq${"id": "shure-beta98ampc", "brand": "Shure", "model": "Beta 98AMP/C", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 4, "quote": "Cartridge Type  Electret Condenser"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 3, "quote": "• Uniform cardioid polar pattern for maximum gain  with drumsticks may loosen it, resulting in signal loss."}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 4, "quote": "All specifications measured with a 48 Vdc phantom power supply. The microphone operates at"}, "note": "Capsula a clip con preamplificatore in linea: richiede phantom."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 4, "quote": "Frequency Response  20 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 4, "quote": "Frequency Response  20 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 2.5, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 4, "quote": "Sensitivity  –50.5 dBV/Pa[1] (2.5 mV)"}}, "impedance_ohm": {"value": 1000, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 4, "quote": "mends a minimum input load impedance of 1000 Ω. Most modern microphone preampli-"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98AMP_Guide", "page": 3, "quote": "XLR connection, a flexible gooseneck, and is packaged"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-beta98ampc', 'shure-beta98amp-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta98hc', 'Shure', 'Beta 98H/C', 'microfono', 'current', 'shure-beta98h-guide', $eq${"id": "shure-beta98hc", "brand": "Shure", "model": "Beta 98H/C", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 3, "quote": "Type  Electret Condenser"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 2, "quote": "Featuring a highly consistent cardioid polar pattern, the"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 3, "quote": "Power Requirements  11 to 52 Vdc phantom  CARTRIDGE"}, "note": "Capsula a clip per fiati: richiede phantom."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 3, "quote": "Frequency Response  20 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 3, "quote": "Frequency Response  20 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 1.6, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 3, "quote": "Sensitivity  −56 dBV/Pa (1.6 mV)"}}, "impedance_ohm": {"value": 150, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 3, "quote": "Output Impedance  150 Ω"}}, "maxSPL_db": {"value": 155, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 3, "quote": "Maximum SPL  155 dB SPL (typical)"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA98H_Guide", "page": 2, "quote": "use a balanced microphone cable: XLR-to-XLR or  MONITOR"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-beta98hc', 'shure-beta98h-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-ksm137', 'Shure', 'KSM137', 'microfono', 'current', 'shure-ksm137-guide', $eq${"id": "shure-ksm137", "brand": "Shure", "model": "KSM137", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 7, "quote": "Cartridge Type ⏎ Electret Condenser"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 3, "quote": "The KSM137 is a premium, end-address, condenser microphone with a cardioid polar pattern engineered for highly critical stu-"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 8, "quote": "[4]All specifications measured with a 48 Vdc phantom power supply. The microphone operates at lower"}, "note": "Condensatore a diaframma piccolo: richiede phantom 11-52 V."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 7, "quote": "Frequency Response ⏎ 20 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 7, "quote": "Frequency Response ⏎ 20 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 14.1, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 7, "quote": "Sensitivity ⏎ –37 dBV/Pa[1] (14.1 mV)"}}, "sensitivity_dbv": {"value": -25.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 8, "quote": "0 , -15 , -25 dB"}}, "impedance_ohm": {"value": 1000, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 5, "quote": "which you connect the microphone. Shure recommends a minimum input load impedance of 1000 Ω. Most modern microphone"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_KSM137_Guide", "page": 4, "quote": "Most modern mixers provide phantom power. You must use a balanced microphone cable: XLR-to-XLR."}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-ksm137', 'shure-ksm137-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta181', 'Shure', 'Beta 181', 'microfono', 'current', 'shure-beta181-guide', $eq${"id": "shure-beta181", "brand": "Shure", "model": "Beta 181", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 6, "quote": "Type ⏎ Electret Condenser"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 3, "quote": "dio environments. Featuring interchangeable cardioid, supercardioid, omnidirectional and bidirectional capsules for superior"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 8, "quote": "[4]All specifications measured with a 48 Vdc phantom power supply. The microphone operates at lower"}, "note": "Capsule intercambiabili: la figura dipende dalla capsula montata."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 6, "quote": "Frequency Response ⏎ 20 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 6, "quote": "Frequency Response ⏎ 20 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 4.7, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 6, "quote": "Sensitivity ⏎ Cardioid  –46.5 dBV/Pa[1] (4.7 mV)"}}, "impedance_ohm": {"value": 1000, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 6, "quote": "which you connect the microphone. Shure recommends a minimum input load impedance of 1000 Ω. Most modern microphone"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_BETA181_Guide", "page": 6, "quote": "Most modern mixers provide phantom power. You must use a balanced microphone cable: XLR-to-XLR."}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-beta181', 'shure-beta181-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-sm7b', 'Shure', 'SM7B', 'microfono', 'current', 'shure-sm7b-guide', $eq${"id": "shure-sm7b", "brand": "Shure", "model": "SM7B", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 9, "quote": "Type ⏎ Dynamic (moving coil)"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 9, "quote": "Polar Pattern ⏎ Cardioid"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 1, "quote": "Cardioid Dynamic Vocal Microphone"}, "note": "Dinamico: phantom non necessaria (vuole molto guadagno dal preamp)."}, "freqResp_lo_hz": {"value": 50, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 9, "quote": "Frequency Response ⏎ 50 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 9, "quote": "Frequency Response ⏎ 50 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 1.12, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 10, "quote": "Sensitivity ⏎ ­59 dBV/Pa[1] (1.12 mV)"}}, "impedance_ohm": {"value": 150, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 10, "quote": "Output Impedance ⏎ 150 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_SM7B_Guide", "page": 4, "quote": "The bracket should fit so the XLR connector faces the rear of the microphone and the Shure logo on the back of the mi­"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-sm7b', 'shure-sm7b-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-tl47', 'Shure', 'TwinPlex TL47', 'microfono', 'current', 'shure-twinplex-tl45-tl47-guide', $eq${"id": "shure-tl47", "brand": "Shure", "model": "TwinPlex TL47", "category": "microfono", "polar": {"value": "omni", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_TwinPlex_TL45-TL47_Guide", "page": 3, "quote": "The Shure TwinPlex subminiature omnidirectional lavaliers are designed to perform better than other 5 mm lavalier micro­"}}, "connector": {"value": "MicroDot / TA4F (per bodypack)", "unit_orig": null, "reliability": "official", "source": {"doc": "Shure_TwinPlex_TL45-TL47_Guide", "page": 4, "quote": "XLR, NC"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('shure-tl47', 'shure-twinplex-tl45-tl47-guide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-e935', 'Sennheiser', 'e 935', 'microfono', 'current', 'sennheiser-e935-spec', $eq${"id": "sennheiser-e935", "brand": "Sennheiser", "model": "e 935", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "Transducer principle  dynamic"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "•  Cardioid pick-up pattern: Insulation from other on-sta-"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "Transducer principle  dynamic"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 40, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "Frequency response  40 - 18,000 Hz"}}, "freqResp_hi_hz": {"value": 18000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "Frequency response  40 - 18,000 Hz"}}, "sensitivity_mvpa": {"value": 2.8, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "DELIVERY INCLUDES  Sensitivity (free field, at  2.8 mV/Pa"}}, "impedance_ohm": {"value": 350, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "Nominal impedance (at  350 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e935_Spec", "page": 1, "quote": "Connector  XLR-3"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-e935', 'sennheiser-e935-spec')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-e945', 'Sennheiser', 'e 945', 'microfono', 'current', 'sennheiser-e945-spec', $eq${"id": "sennheiser-e945", "brand": "Sennheiser", "model": "e 945", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "Transducer principle  dynamic"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "•  Super-cardioid pick-up pattern: Insulation from other"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "Transducer principle  dynamic"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 40, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "Frequency response  40 - 18,000 Hz"}}, "freqResp_hi_hz": {"value": 18000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "Frequency response  40 - 18,000 Hz"}}, "sensitivity_mvpa": {"value": 2.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "DELIVERY INCLUDES  Sensitivity (free field, at  2.0 mV/Pa ±3 dB"}}, "impedance_ohm": {"value": 350, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "Nominal impedance (at  350 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e945_Spec", "page": 1, "quote": "Connector  XLR-3"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-e945', 'sennheiser-e945-spec')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-e865', 'Sennheiser', 'e 865', 'microfono', 'current', 'sennheiser-e865-spec', $eq${"id": "sennheiser-e865", "brand": "Sennheiser", "model": "e 865", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "Transducer principle  pre-polarized condenser"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "Transducer principle  pre-polarized condenser ⏎ Pick-up pattern  super-cardioid"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 2, "quote": "be 150 dB. The microphone shall operate on 12 – 52 V phantom power and shall provide a 3-pin XLR connector. Dimensi-"}, "note": "Condensatore: richiede phantom."}, "freqResp_lo_hz": {"value": 40, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "Frequency response  40 - 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "Frequency response  40 - 20,000 Hz"}}, "sensitivity_mvpa": {"value": 3.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "Sensitivity (free field, at  3 mV/Pa"}}, "impedance_ohm": {"value": 200, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "Nominal impedance (at  200 Ω (balanced)"}}, "maxSPL_db": {"value": 150, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "Max. sound pressure level  150 dB"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e865_Spec", "page": 1, "quote": "sing the very best in condenser microphone technology to  Connector  XLR-3"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-e865', 'sennheiser-e865-spec')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-e902', 'Sennheiser', 'e 902', 'microfono', 'current', 'sennheiser-e902-spec', $eq${"id": "sennheiser-e902", "brand": "Sennheiser", "model": "e 902", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "Transducer principle  dynamic  The microphone shall be a dynamic cardioid designed for"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "Pick-up pattern  cardioid  capsule. The microphone shall be fitted with a hum com-"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "The cardioid e 902 is a dynamic instrument microphone"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "Frequency response  20 - 18,000 Hz  body with an integral stand mount and a shock-mounted"}}, "freqResp_hi_hz": {"value": 18000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "Frequency response  20 - 18,000 Hz  body with an integral stand mount and a shock-mounted"}}, "sensitivity_mvpa": {"value": 0.6, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "Sensitivity (free field)  0.6 mV/Pa (at 60 Hz)"}}, "impedance_ohm": {"value": 350, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "Nominal impedance (at  350 Ω  the sensitivity (free field, no load) shall be 0.2 mV/Pa at 1"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e902_Spec", "page": 1, "quote": "The microphone shall provide a 3-pin XLR connector."}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-e902', 'sennheiser-e902-spec')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-e901', 'Sennheiser', 'e 901', 'microfono', 'current', 'sennheiser-e901-spec', $eq${"id": "sennheiser-e901", "brand": "Sennheiser", "model": "e 901", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "The microphone shall be a half-cardioid pre-polarized  Transducer principle  pre-polarized condenser"}}, "polar": {"value": "half-cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "High-quality pre-polarised condenser microphone with ⏎ half-cardioid pickup pattern, especially suitable for use"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "rate on 48 V phantom power and shall provide a gold-pla-  Power supply  P48"}, "note": "Boundary a superficie: richiede phantom."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "rugged, step-resistant sound inlet basket and shall feature  Frequency response  20 - 20,000 Hz ± 2.5 dB"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "rugged, step-resistant sound inlet basket and shall feature  Frequency response  20 - 20,000 Hz ± 2.5 dB"}}, "sensitivity_mvpa": {"value": 0.5, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "The frequency response shall be 20 Hz – 20,000 Hz and  Sensitivity  -66 dBV/Pa (0.5 mV/Pa)"}}, "sensitivity_dbv": {"value": -66.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "The frequency response shall be 20 Hz – 20,000 Hz and  Sensitivity  -66 dBV/Pa (0.5 mV/Pa)"}}, "impedance_ohm": {"value": 50, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "1 kHz.  Nominal impedance  50 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e901_Spec", "page": 1, "quote": "•  Integrated preamp and gold-plated standard XLR plug,"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-e901', 'sennheiser-e901-spec')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-e614', 'Sennheiser', 'e 614', 'microfono', 'current', 'sennheiser-e614-spec', $eq${"id": "sennheiser-e614", "brand": "Sennheiser", "model": "e 614", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "Transducer principle  pre-polarised condenser  The rugged microphone shall be a super-cardioid pre-pola-"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "Transducer principle  pre-polarised condenser  The rugged microphone shall be a super-cardioid pre-pola-"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "Nominal impedance  50 Ω  The microphone shall operate on 12 – 52 V phantom power"}, "note": "Condensatore a diaframma piccolo: richiede phantom."}, "freqResp_lo_hz": {"value": 40, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "ing applications. The frequency response shall be 40 Hz ⏎ Frequency response  40 - 20,000 Hz  – 20,000 Hz and the sensitivity (free field, no load) shall be"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "ing applications. The frequency response shall be 40 Hz ⏎ Frequency response  40 - 20,000 Hz  – 20,000 Hz and the sensitivity (free field, no load) shall be"}}, "sensitivity_mvpa": {"value": 3.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "Sensitivity (free field,  3 mV/Pa"}}, "impedance_ohm": {"value": 50, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "Nominal impedance shall be 50 Ω, with a min. terminating"}}, "maxSPL_db": {"value": 139, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "Pick-up pattern  super-cardioid  3 mV/P at 1 kHz. Maximum SPL shall be 139 dB at 1 kHz."}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_e614_Spec", "page": 1, "quote": "(at 1 kHz)  and shall provide a 3-pin XLR connector. Dimensions shall"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-e614', 'sennheiser-e614-spec')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-md441', 'Sennheiser', 'MD 441-U', 'microfono', 'current', 'sennheiser-md441-u-quickguide', $eq${"id": "sennheiser-md441", "brand": "Sennheiser", "model": "MD 441-U", "category": "microfono", "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_MD441-U_QuickGuide", "page": 2, "quote": "Pick-up pattern  Supercardioid"}}, "freqResp_lo_hz": {"value": 30, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_MD441-U_QuickGuide", "page": 2, "quote": "Frequency response  30 - 20,000 Hz  1  2  1  2  1  2"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_MD441-U_QuickGuide", "page": 2, "quote": "Frequency response  30 - 20,000 Hz  1  2  1  2  1  2"}}, "sensitivity_mvpa": {"value": 1.8, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_MD441-U_QuickGuide", "page": 2, "quote": "Sensitivity (free field, at 1 kHz)  1,8 mV/Pa ±2 dB"}}, "impedance_ohm": {"value": 200, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_MD441-U_QuickGuide", "page": 2, "quote": "Electrical impedance  200 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_MD441-U_QuickGuide", "page": 1, "quote": "*XLR-3 cable not included"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-md441', 'sennheiser-md441-u-quickguide')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-mkh416', 'Sennheiser', 'MKH 416-P48 U3', 'microfono', 'current', 'sennheiser-mkh416-spec', $eq${"id": "sennheiser-mkh416", "brand": "Sennheiser", "model": "MKH 416-P48 U3", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "10  Transducer principle  RF condenser microphone"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "Pick-up pattern  super-cardioid/lobar"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "250 Hz  4000 Hz  Power supply  48 V ± 4 V phantom powering"}, "note": "Condensatore a radiofrequenza, tubo d'interferenza: richiede P48."}, "freqResp_lo_hz": {"value": 40, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "5  Frequency response  40 - 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "5  Frequency response  40 - 20,000 Hz"}}, "sensitivity_mvpa": {"value": 25.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "25  Sensitivity (free field, no load)  25 mV/PA ± 1 dB"}}, "impedance_ohm": {"value": 25, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "Nominal impedance  25 Ω"}}, "maxSPL_db": {"value": 130, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "Max. sound pressure level  130 dB SPL"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Sennheiser_MKH416_Spec", "page": 2, "quote": "Connector  3-pol. XLR connector"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('sennheiser-mkh416', 'sennheiser-mkh416-spec')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('akg-d112', 'AKG', 'D112 MkII', 'microfono', 'current', 'akg-d112mkii-cutsheet', $eq${"id": "akg-d112", "brand": "AKG", "model": "D112 MkII", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 1, "quote": "PROFESSIONAL DYNAMIC BASS DRUM MICROPHONE"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 2, "quote": "Polar pattern  Cardioid"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 1, "quote": "PROFESSIONAL DYNAMIC BASS DRUM MICROPHONE"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 2, "quote": "Frequency response  20 Hz to 17 kHz (see frequency response trace)"}}, "freqResp_hi_hz": {"value": 17000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 2, "quote": "Frequency response  20 Hz to 17 kHz (see frequency response trace)"}}, "sensitivity_mvpa": {"value": 1.8, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 2, "quote": "Sensitivity  1,8 mV/Pa (-55 dBV)"}}, "sensitivity_dbv": {"value": -55.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 2, "quote": "Sensitivity  1,8 mV/Pa (-55 dBV)"}}, "impedance_ohm": {"value": 210, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 2, "quote": "Electrical impedance  210 ohms"}}, "maxSPL_db": {"value": 160, "unit_orig": "dB", "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 1, "quote": "The D112 MKII cardioid dynamic mic can handle more than 160 dB SPL without distortion. Its large diaphragm"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D112MkII_CutSheet", "page": 2, "quote": "Connector  3-pin XLR (pin 2 hot)"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('akg-d112', 'akg-d112mkii-cutsheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('akg-c451b', 'AKG', 'C451 B', 'microfono', 'current', 'akg-c451b-cutsheet', $eq${"id": "akg-c451b", "brand": "AKG", "model": "C451 B", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 1, "quote": "REFERENCE SMALL-DIAPHRAGM CONDENSER MICROPHONE"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Polar Patterns:  Cardioid"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Powering Interface ⏎ Voltage:  9 to 52 V"}, "note": "Condensatore a diaframma piccolo: richiede phantom."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Audio frequency bandwidth:  20 to 20000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Audio frequency bandwidth:  20 to 20000 Hz"}}, "sensitivity_mvpa": {"value": 9.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Sensitivity:  9 mV/Pa"}}, "sensitivity_dbv": {"value": -20.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Preattenuation Pad:  -10, -20 dB"}}, "impedance_ohm": {"value": 200, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Electrical impedance:  200 Ohms"}}, "maxSPL_db": {"value": 155, "unit_orig": "dB", "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 1, "quote": "Impressive sound pressure level capability of 155dB SPL"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C451B_CutSheet", "page": 2, "quote": "Type:  Balanced XLR"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('akg-c451b', 'akg-c451b-cutsheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('akg-c214', 'AKG', 'C214', 'microfono', 'current', 'akg-c214-cutsheet', $eq${"id": "akg-c214", "brand": "AKG", "model": "C214", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 2, "quote": "Capsule:  One Inch Large Diaphragm Condenser"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 2, "quote": "Polar Pattern:  Cardioid"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 2, "quote": "Phantom Power:  12 to 52 V (IEC 61938)"}, "note": "Condensatore a diaframma grande: richiede phantom."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 2, "quote": "Frequency Range:  20 to 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 2, "quote": "Frequency Range:  20 to 20,000 Hz"}}, "sensitivity_mvpa": {"value": 20.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 2, "quote": "Sensitivity:  20 mV/Pa (-34 dBV)"}}, "sensitivity_dbv": {"value": -34.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 2, "quote": "Sensitivity:  20 mV/Pa (-34 dBV)"}}, "maxSPL_db": {"value": 143, "unit_orig": "dB", "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 1, "quote": "Incredible 143dB dynamic range (up to 156 dB SPL)"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_C214_CutSheet", "page": 1, "quote": "construction quality with a modern scratch-resistant finish, a dent-resistant, metal grille and a gold-plated XLR-type output."}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('akg-c214', 'akg-c214-cutsheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('akg-d5', 'AKG', 'D5', 'microfono', 'current', 'akg-d5s-cutsheet', $eq${"id": "akg-d5", "brand": "AKG", "model": "D5", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 1, "quote": "PROFESSIONAL DYNAMIC VOCAL MICROPHONE"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 1, "quote": "supercardioid polar pattern ensures maximum gain before feedback."}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 1, "quote": "PROFESSIONAL DYNAMIC VOCAL MICROPHONE"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 70, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 2, "quote": "Audio frequency bandwidth:  70 to 20000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 2, "quote": "Audio frequency bandwidth:  70 to 20000 Hz"}}, "sensitivity_mvpa": {"value": 2.6, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 2, "quote": "Sensitivity:  2.6 mV/Pa"}}, "impedance_ohm": {"value": 600, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 2, "quote": "Electrical impedance:  600 Ohms"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D5S_CutSheet", "page": 2, "quote": "Type:  Balanced XLR"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('akg-d5', 'akg-d5s-cutsheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('akg-d40', 'AKG', 'D40', 'microfono', 'current', 'akg-d40-cutsheet', $eq${"id": "akg-d40", "brand": "AKG", "model": "D40", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 1, "quote": "PROFESSIONAL DYNAMIC INSTRUMENT MICROPHONE"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 1, "quote": "Cardioid polar pattern"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 1, "quote": "PROFESSIONAL DYNAMIC INSTRUMENT MICROPHONE"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 50, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 2, "quote": "Audio frequency bandwidth:  50 to 20000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 2, "quote": "Audio frequency bandwidth:  50 to 20000 Hz"}}, "sensitivity_mvpa": {"value": 2.5, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 2, "quote": "Sensitivity:  2.5 mV/Pa"}}, "impedance_ohm": {"value": 600, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 2, "quote": "Electrical impedance:  ≥ 600 Ohms"}}, "maxSPL_db": {"value": 156, "unit_orig": "dB", "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 1, "quote": "Highest sound pressure levels up to 156dB"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "AKG_D40_CutSheet", "page": 2, "quote": "Type:  Balanced XLR"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('akg-d40', 'akg-d40-cutsheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('ev-re20', 'Electro-Voice', 'RE20', 'microfono', 'current', 'electrovoice-re20-datasheet', $eq${"id": "ev-re20", "brand": "Electro-Voice", "model": "RE20", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "ElectroVoice_RE20_DataSheet", "page": 1, "quote": "The Electro-Voice RE20 is a professional-quality dynamic cardioid  Element Type:  Dynamic"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "ElectroVoice_RE20_DataSheet", "page": 1, "quote": "a very wide frequency range. The wide frequency response, coupled  Polar Pattern:  Cardioid"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "ElectroVoice_RE20_DataSheet", "page": 1, "quote": "Dynamic Cardioid"}, "note": "Dinamico Variable-D: phantom non necessaria."}, "freqResp_lo_hz": {"value": 45, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "ElectroVoice_RE20_DataSheet", "page": 1, "quote": "reinforcement applications requiring essentially flat response over  Frequency Response:  45 Hz - 18,000 Hz"}}, "freqResp_hi_hz": {"value": 18000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "ElectroVoice_RE20_DataSheet", "page": 1, "quote": "reinforcement applications requiring essentially flat response over  Frequency Response:  45 Hz - 18,000 Hz"}}, "sensitivity_mvpa": {"value": 1.5, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "ElectroVoice_RE20_DataSheet", "page": 1, "quote": "to the finest condenser cardioid microphones and an easily oper-  Sensitivity, Open Circuit  1.5 mV/pascal"}}, "impedance_ohm": {"value": 150, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "ElectroVoice_RE20_DataSheet", "page": 1, "quote": "with excellent transient response, make the RE20 easily comparable  Impedance:  150 ohms balanced"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('ev-re20', 'electrovoice-re20-datasheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('beyerdynamic-m88', 'beyerdynamic', 'M 88', 'microfono', 'current', 'beyerdynamic-m88tg-datasheet', $eq${"id": "beyerdynamic-m88", "brand": "beyerdynamic", "model": "M 88", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "• Flexible use  Transducer type . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Dynamic"}}, "polar": {"value": "hypercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "• Hypercardioid polar pattern  Operating principle . . . . . . . . . . . . . . . . . . . Pressure gradient"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "Dynamic Microphone"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 30, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "• Made in Germany  Frequency response . . . . . . . . . . . . . . . . . . . . . . 30 - 20,000 Hz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "• Made in Germany  Frequency response . . . . . . . . . . . . . . . . . . . . . . 30 - 20,000 Hz"}}, "sensitivity_mvpa": {"value": 2.9, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "Open circuit voltage . . . . . . . . . . . . . . . . . 2.9 mV/Pa (-51 dBV)"}}, "sensitivity_dbv": {"value": -51.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "Open circuit voltage . . . . . . . . . . . . . . . . . 2.9 mV/Pa (-51 dBV)"}}, "impedance_ohm": {"value": 200, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "The M 88 TG impresses with its flexible application options.  Nominal impedance . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 200 Ω"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Beyerdynamic_M88TG_Datasheet", "page": 1, "quote": "more, it has a high gain before feedback making it  Connection . . . . . . . . . . . . . . . . . . . . . . . . . . . . . XLR, 3-pin, male"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('beyerdynamic-m88', 'beyerdynamic-m88tg-datasheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('rode-nt5', 'RODE', 'NT5', 'microfono', 'current', 'rode-nt5-datasheet', $eq${"id": "rode-nt5", "brand": "RODE", "model": "NT5", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "The NT5 is a premium ½-inch diaphragm true condenser"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "accurate cardioid polar pattern and wide frequency response"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "Power Requirement:  P48 phantom power"}, "note": "Condensatore a diaframma piccolo: richiede phantom 24/48 V."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "Frequency Response:  20Hz - 20kHz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "Frequency Response:  20Hz - 20kHz"}}, "sensitivity_dbv": {"value": -38.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "Sensitivity:  -38 dBV (12 mV @ 94 dB SPL)"}}, "maxSPL_db": {"value": 143, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "Maximum SPL:  143 dB SPL"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT5_Datasheet", "page": 1, "quote": "3 pin XLR, balanced output between Pin2"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('rode-nt5', 'rode-nt5-datasheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('rode-nt1-5th', 'RODE', 'NT1 5th Generation', 'microfono', 'current', 'rode-nt1-5thgen-datasheet', $eq${"id": "rode-nt1-5th", "brand": "RODE", "model": "NT1 5th Generation", "category": "microfono", "principle": {"value": "condenser", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "• Large-diaphragm (1-inch) gold-sputtered condenser capsule"}}, "polar": {"value": "cardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "with bipolar output buffer ⏎ USB connectivity for connecting to an audio interface, mixer or console,  Polar Pattern:  Cardioid"}}, "phantom": {"value": "required", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "Analogue Power  Via XLR: P48"}, "note": "Condensatore a diaframma grande: richiede phantom (in XLR)."}, "freqResp_lo_hz": {"value": 20, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "Frequency Range:  20Hz - 20kHz"}}, "freqResp_hi_hz": {"value": 20000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "Frequency Range:  20Hz - 20kHz"}}, "sensitivity_dbv": {"value": -32.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "revolutionary features complement the warm silky character, extended  Sensitivity:  -32 dB re 1 Volt/Pascal (25"}}, "impedance_ohm": {"value": 100, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "Output Impedance:  100Ω"}}, "maxSPL_db": {"value": 142, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "Maximum SPL:  142 dB SPL"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Rode_NT1-5thGen_Datasheet", "page": 1, "quote": "WARRANTY  XLR & USB  DIGITAL OUTPUT  CAPSULE"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('rode-nt1-5th', 'rode-nt1-5thgen-datasheet')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('se-v7', 'sE Electronics', 'V7', 'microfono', 'current', 'se-v7-usermanual', $eq${"id": "se-v7", "brand": "sE Electronics", "model": "V7", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 2, "quote": "The V7 and V3 are dynamic hand-held microphones ideal for vocal applications on the stage. Thanks"}}, "polar": {"value": "supercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 2, "quote": "With its super-cardioid pattern, the sophisticated capsule design also helps isolate your voice or"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 2, "quote": "The V7 and V3 are dynamic hand-held microphones ideal for vocal applications on the stage. Thanks"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 40, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 3, "quote": "Frequency range  40 – 19,000 Hz  50 – 16,000 Hz"}}, "freqResp_hi_hz": {"value": 19000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 3, "quote": "Frequency range  40 – 19,000 Hz  50 – 16,000 Hz"}}, "sensitivity_mvpa": {"value": 2.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 3, "quote": "Sensitivity  2.0 mV/Pa -54 dBV  2.5 mV/Pa -52 dBV"}}, "sensitivity_dbv": {"value": -54.0, "unit_orig": "dBV/Pa", "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 3, "quote": "Sensitivity  2.0 mV/Pa -54 dBV  2.5 mV/Pa -52 dBV"}}, "impedance_ohm": {"value": 300, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 3, "quote": "Electrical Impedance  300 ohms  600 ohms"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "sE_V7_UserManual", "page": 2, "quote": "The robust all-metal construction, stainless spring steel mesh grille and gold-plated XLR contacts"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('se-v7', 'se-v7-usermanual')
on conflict do nothing;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('audix-om5', 'Audix', 'OM5', 'microfono', 'current', 'audix-om5-specsheet', $eq${"id": "audix-om5", "brand": "Audix", "model": "OM5", "category": "microfono", "principle": {"value": "dynamic", "unit_orig": null, "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 2, "quote": "Transducer Type  Dynamic"}}, "polar": {"value": "hypercardioid", "unit_orig": null, "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 1, "quote": "hypercardioid polar pattern which helps to isolate the vocals from the rest of the"}}, "phantom": {"value": "no", "unit_orig": null, "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 1, "quote": "OM5  Dynamic Vocal Microphone"}, "note": "Dinamico: phantom non necessaria."}, "freqResp_lo_hz": {"value": 48, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 1, "quote": "instruments on stage. With a wide frequency range of 48 Hz - 19 kHz, the OM5"}}, "freqResp_hi_hz": {"value": 19000, "unit_orig": "Hz", "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 1, "quote": "instruments on stage. With a wide frequency range of 48 Hz - 19 kHz, the OM5"}}, "sensitivity_mvpa": {"value": 2.0, "unit_orig": "mV/Pa", "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 2, "quote": "Sensitivity  2 mV / Pa @ 1k"}}, "impedance_ohm": {"value": 200, "unit_orig": "Ohm", "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 2, "quote": "Output Impedance  200 ohms"}}, "maxSPL_db": {"value": 144, "unit_orig": "dB", "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 2, "quote": "Pa at 1 kHz and a sound pressure level ≥144 dB. The microphone body shall be"}}, "connector": {"value": "XLR3M", "unit_orig": null, "reliability": "official", "source": {"doc": "Audix_OM5_SpecSheet", "page": 1, "quote": "E-coat finish, dent resistant steel mesh grill and gold plated XLR connector.  FEATURES"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, primary_source_doc=excluded.primary_source_doc, updated_at=now();
insert into equip_product_document (product_id, document_id) values ('audix-om5', 'audix-om5-specsheet')
on conflict do nothing;
commit;
