-- equip-seed-mic.sql — 7 microfoni aggiuntivi (default dell'app + specifiche ufficiali, ricerca web 18/07/2026)
-- Idempotente (upsert). Eseguire nel SQL editor Supabase DOPO la 0015 e il seed principale.
begin;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('dpa-4099-manual', 'DPA', '4099', 'microfono', 'SpecSheet', 'en', 'https://www.dpamicrophones.com/microphones/instrument/4099', 'DPA_4099_Manual.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('dpa-4066-manual', 'DPA', '4066', 'microfono', 'SpecSheet', 'en', 'https://www.dpamicrophones.com/microphones/headset-and-earset/4066', 'DPA_4066_Manual.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('shure-sm81-specsheet', 'Shure', 'SM81', 'microfono', 'SpecSheet', 'en', 'https://www.shure.com/en-US/products/microphones/sm81', 'Shure_SM81_SpecSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('shure-beta58a-specsheet', 'Shure', 'Beta 58A', 'microfono', 'SpecSheet', 'en', 'https://www.shure.com/en-US/products/microphones/beta_58a', 'Shure_Beta58A_SpecSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('shure-beta91a-specsheet', 'Shure', 'Beta 91A', 'microfono', 'SpecSheet', 'en', 'https://www.shure.com/en-US/products/microphones/beta_91a', 'Shure_Beta91A_SpecSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('audix-d6-specsheet', 'Audix', 'D6', 'microfono', 'SpecSheet', 'en', 'https://audixusa.com/us-en/professional-dynamic-instrument-microphone-ax-d6/', 'Audix_D6_SpecSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('sennheiser-e904-specsheet', 'Sennheiser', 'e 904', 'microfono', 'SpecSheet', 'en', 'https://www.sennheiser.com/en-us/catalog/products/microphones/e-904/e-904-500200', 'Sennheiser_e904_SpecSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('dpa-4099', 'DPA', '4099', 'microfono', 'current', 'dpa-4099-manual', $eq${"id":"dpa-4099","brand":"DPA","model":"4099","category":"microfono","principle":{"value":"condenser","unit_orig":null,"reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"pre-polarized condenser microphone"}},"polar":{"value":"supercardioid","unit_orig":null,"reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"The 4099 features a supercardioid polar pattern"}},"phantom":{"value":"required","unit_orig":null,"reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"with DAD6001-BC or DAD4099-BC, it supports P48 phantom power (48V)"},"note":"Condensatore: richiede P48 (via adattatore XLR) o alimentazione 5-10V per wireless."},"sensitivity_mvpa":{"value":6,"unit_orig":"mV/Pa","reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"6 mV/Pa; -44 dB re. 1 V/Pa"}},"sensitivity_dbv":{"value":-44,"unit_orig":"dBV/Pa","reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"-44 dB re. 1 V/Pa"}},"freqResp_lo_hz":{"value":20,"unit_orig":"Hz","reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"frequency response is 20 Hz - 20 kHz"}},"freqResp_hi_hz":{"value":20000,"unit_orig":"Hz","reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"frequency response is 20 Hz - 20 kHz"}},"connector":{"value":"MicroDot (→ XLR via adattatore / wireless)","unit_orig":"","reliability":"official","source":{"doc":"DPA_4099_Manual","page":1,"quote":"through a DPA adapter"},"note":"Capsula a clip per strumento; uscita MicroDot verso XLR (DAD) o bodypack."},"maxSPL_db":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"Versioni SPL diverse per strumento; non un singolo valore."},"pad_db":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"Nessun pad; le versioni Loud/Extreme SPL gestiscono livelli alti."}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('dpa-4066', 'DPA', '4066', 'microfono', 'current', 'dpa-4066-manual', $eq${"id":"dpa-4066","brand":"DPA","model":"4066","category":"microfono","principle":{"value":"condenser","unit_orig":null,"reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"pre-polarized condenser cartridge principle"}},"polar":{"value":"omni","unit_orig":null,"reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"omnidirectional directional pattern"}},"phantom":{"value":"required","unit_orig":null,"reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"with the DAD6001-BC it supports P48 Phantom Power"},"note":"Headset condensatore: P48 via adattatore o 5-10V wireless."},"sensitivity_mvpa":{"value":6,"unit_orig":"mV/Pa","reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"Sensitivity is 6 mV/Pa at -44 dB re. 1 V/Pa"}},"sensitivity_dbv":{"value":-44,"unit_orig":"dBV/Pa","reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"-44 dB re. 1 V/Pa"}},"freqResp_lo_hz":{"value":20,"unit_orig":"Hz","reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"frequency response is 20 Hz - 20 kHz"}},"freqResp_hi_hz":{"value":20000,"unit_orig":"Hz","reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"frequency response is 20 Hz - 20 kHz"}},"maxSPL_db":{"value":134,"unit_orig":"dB","reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"the CORE version handles 134 dB SPL RMS"}},"connector":{"value":"MicroDot (→ XLR via adattatore / wireless)","unit_orig":"","reliability":"official","source":{"doc":"DPA_4066_Manual","page":1,"quote":"through DPA adapter"},"note":"Archetto; uscita MicroDot verso XLR (DAD) o bodypack."}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-sm81', 'Shure', 'SM81', 'microfono', 'current', 'shure-sm81-specsheet', $eq${"id":"shure-sm81","brand":"Shure","model":"SM81","category":"microfono","principle":{"value":"condenser","unit_orig":null,"reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"condenser microphone"}},"polar":{"value":"cardioid","unit_orig":null,"reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"cardioid polar pattern, uniform with frequency"}},"phantom":{"value":"required","unit_orig":null,"reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"requires supply voltage of 11 to 52 Vdc"},"note":"Condensatore: richiede phantom 11-52 V."},"freqResp_lo_hz":{"value":20,"unit_orig":"Hz","reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"linear frequency response from 20Hz to 20,000Hz"}},"freqResp_hi_hz":{"value":20000,"unit_orig":"Hz","reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"20Hz to 20,000Hz"}},"pad_db":{"value":[10],"unit_orig":"dB","reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"lockable -10 dB pad"}},"hpfBuiltin":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"switchable low-pass filter ... 6 dB/octave or 18 dB/octave"}},"maxSPL_db":{"value":146,"unit_orig":"dB","reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"SPL handling of 146 dB (with the pad on)"}},"connector":{"value":"XLR3M","unit_orig":null,"reliability":"official","source":{"doc":"Shure_SM81_SpecSheet","page":1,"quote":"uses an XLR cable"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta58a', 'Shure', 'Beta 58A', 'microfono', 'current', 'shure-beta58a-specsheet', $eq${"id":"shure-beta58a","brand":"Shure","model":"Beta 58A","category":"microfono","principle":{"value":"dynamic","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta58A_SpecSheet","page":1,"quote":"supercardioid dynamic vocal microphone"}},"polar":{"value":"supercardioid","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta58A_SpecSheet","page":1,"quote":"true supercardioid pattern throughout its frequency range"}},"phantom":{"value":"no","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta58A_SpecSheet","page":1,"quote":"dynamic vocal microphone"},"note":"Dinamico: phantom non necessaria."},"freqResp_lo_hz":{"value":50,"unit_orig":"Hz","reliability":"official","source":{"doc":"Shure_Beta58A_SpecSheet","page":1,"quote":"Frequency Response: 50Hz-16kHz"}},"freqResp_hi_hz":{"value":16000,"unit_orig":"Hz","reliability":"official","source":{"doc":"Shure_Beta58A_SpecSheet","page":1,"quote":"50Hz-16kHz"}},"impedance_ohm":{"value":150,"unit_orig":"Ohm","reliability":"official","source":{"doc":"Shure_Beta58A_SpecSheet","page":1,"quote":"Impedance: 150 ohms"}},"connector":{"value":"XLR3M","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta58A_SpecSheet","page":1,"quote":"XLR"}},"pad_db":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"Nessun pad."}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('shure-beta91a', 'Shure', 'Beta 91A', 'microfono', 'current', 'shure-beta91a-specsheet', $eq${"id":"shure-beta91a","brand":"Shure","model":"Beta 91A","category":"microfono","principle":{"value":"condenser","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"boundary condenser microphone with integrated preamplifier"}},"polar":{"value":"half-cardioid","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"uniform half-cardioid polar pattern"}},"phantom":{"value":"required","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"operated with phantom power ... 11V and 52V"},"note":"Condensatore boundary con preamp integrato: richiede phantom 11-52 V."},"sensitivity_mvpa":{"value":3.8,"unit_orig":"mV/Pa","reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"sensitivity of 3.8mV/Pa"}},"freqResp_lo_hz":{"value":20,"unit_orig":"Hz","reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"frequency range of 20Hz to 20kHz"}},"freqResp_hi_hz":{"value":20000,"unit_orig":"Hz","reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"20Hz to 20kHz"}},"maxSPL_db":{"value":155,"unit_orig":"dB","reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"maximum sound pressure level of 155dB at a load of 2,500 ohms"}},"connector":{"value":"XLR3M","unit_orig":null,"reliability":"official","source":{"doc":"Shure_Beta91A_SpecSheet","page":1,"quote":"XLR connection"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('audix-d6', 'Audix', 'D6', 'microfono', 'current', 'audix-d6-specsheet', $eq${"id":"audix-d6","brand":"Audix","model":"D6","category":"microfono","principle":{"value":"dynamic","unit_orig":null,"reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"Transducer Type: Dynamic"}},"polar":{"value":"cardioid","unit_orig":null,"reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"Polar Pattern: Cardioid"}},"phantom":{"value":"no","unit_orig":null,"reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"Transformerless design ... Dynamic"},"note":"Dinamico: phantom non necessaria."},"sensitivity_mvpa":{"value":0.8,"unit_orig":"mV/Pa","reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"Sensitivity: 0.8 mV / Pa @ 1k"}},"freqResp_lo_hz":{"value":30,"unit_orig":"Hz","reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"Frequency Response: 30 Hz - 15 kHz"}},"freqResp_hi_hz":{"value":15000,"unit_orig":"Hz","reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"30 Hz - 15 kHz"}},"impedance_ohm":{"value":280,"unit_orig":"Ohm","reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"Output Impedance: 280 Ohms"}},"maxSPL_db":{"value":144,"unit_orig":"dB","reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"Maximum SPL in excess of 144 dB"}},"connector":{"value":"XLR3M","unit_orig":null,"reliability":"official","source":{"doc":"Audix_D6_SpecSheet","page":1,"quote":"balanced output"},"note":"Uscita bilanciata XLR."}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('sennheiser-e904', 'Sennheiser', 'e 904', 'microfono', 'current', 'sennheiser-e904-specsheet', $eq${"id":"sennheiser-e904","brand":"Sennheiser","model":"e 904","category":"microfono","principle":{"value":"dynamic","unit_orig":null,"reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"dynamic cardioid microphone"}},"polar":{"value":"cardioid","unit_orig":null,"reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"cardioid polar pattern"}},"phantom":{"value":"no","unit_orig":null,"reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"dynamic ... microphone"},"note":"Dinamico: phantom non necessaria."},"sensitivity_mvpa":{"value":2,"unit_orig":"mV/Pa","reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"sensitivity ... (1kHz) is 2 mV/Pa"}},"freqResp_lo_hz":{"value":40,"unit_orig":"Hz","reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"frequency response of 40Hz-18kHz"}},"freqResp_hi_hz":{"value":18000,"unit_orig":"Hz","reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"40Hz-18kHz"}},"impedance_ohm":{"value":350,"unit_orig":"Ohm","reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"nominal impedance of 350"}},"weight_g":{"value":125,"unit_orig":"g","reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"weighs 125 grams"}},"connector":{"value":"XLR3M","unit_orig":null,"reliability":"official","source":{"doc":"Sennheiser_e904_SpecSheet","page":1,"quote":"connector is XLR-3"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
commit;
