-- equip-seed-pa.sql — 4 sistemi PA (line array + sub, specifiche ufficiali, ricerca web 18/07/2026)
-- Idempotente (upsert). Eseguire nel SQL editor Supabase DOPO la 0015.
begin;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('lacoustics-karaii-specsheet', 'L-Acoustics', 'Kara II', 'line_array', 'SpecSheet', 'en', 'https://www.l-acoustics.com/products/kara-ii/', 'LAcoustics_KaraII_SpecSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('lacoustics-ks28-specsheet', 'L-Acoustics', 'KS28', 'subwoofer', 'SpecSheet', 'en', 'https://www.l-acoustics.com/products/ks28/', 'LAcoustics_KS28_SpecSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('dbaudio-gsl8-datasheet', 'd&b audiotechnik', 'GSL8', 'line_array', 'SpecSheet', 'en', 'https://www.dbaudio.com/global/en/products/all/series/sl-series/gsl8/', 'dbaudio_GSL8_Datasheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('dbaudio-b22-datasheet', 'd&b audiotechnik', 'B22-SUB', 'subwoofer', 'SpecSheet', 'en', 'https://www.dbaudio.com/global/en/products/subwoofers/b22-sub/', 'dbaudio_B22_Datasheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('lacoustics-kara2', 'L-Acoustics', 'Kara II', 'line_array', 'current', 'lacoustics-karaii-specsheet', $eq${"id":"lacoustics-kara2","brand":"L-Acoustics","model":"Kara II","category":"line_array","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"LAcoustics_KaraII_SpecSheet","page":1,"quote":"2-way active configuration"},"note":"Passiva, pilotata da amplificatore L-Acoustics (LA-RAK)."},"transducers":{"value":"2×8\" LF + 1×3\" HF compression","unit_orig":"","reliability":"official","source":{"doc":"LAcoustics_KaraII_SpecSheet","page":1,"quote":"2 × 8″ low-frequency drivers and 1 × 3″ high-frequency compression driver"}},"freqResp_lo_hz":{"value":55,"unit_orig":"Hz","reliability":"official","source":{"doc":"LAcoustics_KaraII_SpecSheet","page":1,"quote":"bandwidth of 55Hz-20KHz"}},"freqResp_hi_hz":{"value":20000,"unit_orig":"Hz","reliability":"official","source":{"doc":"LAcoustics_KaraII_SpecSheet","page":1,"quote":"55Hz-20KHz"}},"maxSPL_db":{"value":142,"unit_orig":"dB","reliability":"official","source":{"doc":"LAcoustics_KaraII_SpecSheet","page":1,"quote":"maximum SPL of 142 dB"}},"dispersion":{"value":"70°/110° sym o 90° asym (H) × 10° (V), Panflex","unit_orig":"","reliability":"official","source":{"doc":"LAcoustics_KaraII_SpecSheet","page":1,"quote":"four horizontal directivity patterns: 70° or 110° symmetrical or 90° asymmetrical ... vertical directivity is 10°"}},"weight_kg":{"value":26,"unit_orig":"kg","reliability":"official","source":{"doc":"LAcoustics_KaraII_SpecSheet","page":1,"quote":"weighs 26 kg (57 lb)"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('lacoustics-ks28', 'L-Acoustics', 'KS28', 'subwoofer', 'current', 'lacoustics-ks28-specsheet', $eq${"id":"lacoustics-ks28","brand":"L-Acoustics","model":"KS28","category":"subwoofer","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"LAcoustics_KS28_SpecSheet","page":1,"quote":"Nominal Impedance: 4 Ω"},"note":"Passivo, pilotato da amplificatore L-Acoustics."},"transducers":{"value":"2×18\" high excursion, bass-reflex","unit_orig":"","reliability":"official","source":{"doc":"LAcoustics_KS28_SpecSheet","page":1,"quote":"Two 18\" high excursion direct-radiating transducers mounted in a bass-reflex enclosure"}},"freqResp_lo_hz":{"value":25,"unit_orig":"Hz","reliability":"official","source":{"doc":"LAcoustics_KS28_SpecSheet","page":1,"quote":"Low Frequency Limit (-10 dB): 25 Hz"}},"maxSPL_db":{"value":143,"unit_orig":"dB","reliability":"official","source":{"doc":"LAcoustics_KS28_SpecSheet","page":1,"quote":"Maximum SPL: 143 dB"}},"dispersion":{"value":"standard o cardioide","unit_orig":"","reliability":"official","source":{"doc":"LAcoustics_KS28_SpecSheet","page":1,"quote":"Directivity: Standard or cardioid"}},"weight_kg":{"value":79,"unit_orig":"kg","reliability":"official","source":{"doc":"LAcoustics_KS28_SpecSheet","page":1,"quote":"79 kg (or approximately 174 lbs)"}},"dims_w_mm":{"value":1351,"unit_orig":"mm","reliability":"official","source":{"doc":"LAcoustics_KS28_SpecSheet","page":1,"quote":"53.2\" x 28.3\" x 21.7\""},"note":"53.2\" ≈ 1351 mm."}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('dbaudio-gsl8', 'd&b audiotechnik', 'GSL8', 'line_array', 'current', 'dbaudio-gsl8-datasheet', $eq${"id":"dbaudio-gsl8","brand":"d&b audiotechnik","model":"GSL8","category":"line_array","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"dbaudio_GSL8_Datasheet","page":1,"quote":"The d&b D80 amplifier is required to drive the GSL8"},"note":"Passiva; richiede amplificatore d&b D80 (2 canali per GSL8)."},"transducers":{"value":"2×14\" LF fwd + 2×10\" LF side + 10\" MF + 3×1.4\" HF (coax)","unit_orig":"","reliability":"official","source":{"doc":"dbaudio_GSL8_Datasheet","page":1,"quote":"two 14\" neodymium forward facing LF drivers and two side firing 10\" ... MF horn with a 10\" driver and three 1.4\" ... HF compression drivers"}},"freqResp_lo_hz":{"value":45,"unit_orig":"Hz","reliability":"official","source":{"doc":"dbaudio_GSL8_Datasheet","page":1,"quote":"frequency response extends from 45 Hz to above 18 kHz"}},"freqResp_hi_hz":{"value":18000,"unit_orig":"Hz","reliability":"official","source":{"doc":"dbaudio_GSL8_Datasheet","page":1,"quote":"45 Hz to above 18 kHz"}},"maxSPL_db":{"value":150,"unit_orig":"dB","reliability":"official","source":{"doc":"dbaudio_GSL8_Datasheet","page":1,"quote":"Maximum sound pressure ... is 150 dB"}},"dispersion":{"value":"80° costante (H)","unit_orig":"","reliability":"official","source":{"doc":"dbaudio_GSL8_Datasheet","page":1,"quote":"80° constant directivity dispersion pattern in the horizontal plane"}},"weight_kg":{"value":80,"unit_orig":"kg","reliability":"official","source":{"doc":"dbaudio_GSL8_Datasheet","page":1,"quote":"176 lbs (approximately 80 kg)"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('dbaudio-b22', 'd&b audiotechnik', 'B22-SUB', 'subwoofer', 'current', 'dbaudio-b22-datasheet', $eq${"id":"dbaudio-b22","brand":"d&b audiotechnik","model":"B22-SUB","category":"subwoofer","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"dbaudio_B22_Datasheet","page":1,"quote":"power handling capacity is 1000 W RMS"},"note":"Passivo, pilotato da amplificatore d&b."},"transducers":{"value":"2×18\" long excursion, bandpass horn","unit_orig":"","reliability":"official","source":{"doc":"dbaudio_B22_Datasheet","page":1,"quote":"two long excursion 18\" drivers built into a bandpass horn cabinet design"}},"freqResp_lo_hz":{"value":37,"unit_orig":"Hz","reliability":"official","source":{"doc":"dbaudio_B22_Datasheet","page":1,"quote":"standard mode, which operates from 37 Hz to 90 Hz"}},"freqResp_hi_hz":{"value":90,"unit_orig":"Hz","reliability":"official","source":{"doc":"dbaudio_B22_Datasheet","page":1,"quote":"37 Hz to 90 Hz"}},"maxSPL_db":{"value":143,"unit_orig":"dB","reliability":"official","source":{"doc":"dbaudio_B22_Datasheet","page":1,"quote":"maximum sound pressure of at least 143 dB"}},"weight_kg":{"value":106,"unit_orig":"kg","reliability":"official","source":{"doc":"dbaudio_B22_Datasheet","page":1,"quote":"weigh no more than 106 kg (234 lb)"}},"dims_w_mm":{"value":1160,"unit_orig":"mm","reliability":"official","source":{"doc":"dbaudio_B22_Datasheet","page":1,"quote":"1160 x 585 x 1046 mm"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
commit;
