-- equip-seed-stagebox.sql — 3 stage box comuni (specifiche ufficiali, ricerca web 18/07/2026)
-- Idempotente (upsert). Eseguire nel SQL editor Supabase DOPO la 0015.
begin;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('yamaha-rio1608-d2-spec', 'Yamaha', 'Rio1608-D2', 'stagebox', 'SpecSheet', 'en', 'https://usa.yamaha.com/products/proaudio/interfaces/r_series_adda_2/index.html', 'Yamaha_Rio1608-D2_Spec.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('midas-dl16-manual', 'Midas', 'DL16', 'stagebox', 'SpecSheet', 'en', 'https://k--b.org/files/dl16.pdf', 'Midas_DL16_Manual.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('midas-dl32-manual', 'Midas', 'DL32', 'stagebox', 'SpecSheet', 'en', 'https://www.midasconsoles.com/product.html?modelCode=P0B3I', 'Midas_DL32_Manual.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('yamaha-rio1608-d2', 'Yamaha', 'Rio1608-D2', 'stagebox', 'current', 'yamaha-rio1608-d2-spec', $eq${"id":"yamaha-rio1608-d2","brand":"Yamaha","model":"Rio1608-D2","category":"stagebox","inputs":{"value":16,"unit_orig":null,"reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"16 analog inputs"}},"outputs":{"value":8,"unit_orig":null,"reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"8 analog outputs"}},"protocol":{"value":"Dante","unit_orig":null,"reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"connects directly to a Dante digital audio network"}},"sampleRate_khz":{"value":96,"unit_orig":"kHz","reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"up to 96kHz"}},"phantom":{"value":"yes","unit_orig":null,"reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"R Series ... recallable mic preamps"},"note":"Preampli con +48V commutabile per canale."},"power_W":{"value":72,"unit_orig":"W","reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"Power consumption is 72W"}},"voltage_range":{"value":"100-240 V","unit_orig":"V","reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"power requirements are 100-240V, 50/60Hz"}},"weight_kg":{"value":9.6,"unit_orig":"kg","reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"Net Weight: 9.6 kg (21.2 lbs)"}},"redundant":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"Redundant connections are supported with primary and secondary connectors"}},"connectors":{"value":"in/out: XLR; rete: 2× etherCON (Primary/Secondary)","unit_orig":"","reliability":"official","source":{"doc":"Yamaha_Rio1608-D2_Spec","page":1,"quote":"primary and secondary connectors"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('midas-dl16', 'Midas', 'DL16', 'stagebox', 'current', 'midas-dl16-manual', $eq${"id":"midas-dl16","brand":"Midas","model":"DL16","category":"stagebox","inputs":{"value":16,"unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL16_Manual","page":1,"quote":"16 ... mic"},"note":"DL16: 16 ingressi mic/line, 8 uscite (formato compatto della serie DL)."},"outputs":{"value":8,"unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL16_Manual","page":1,"quote":"8 out"}},"protocol":{"value":"AES50","unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL16_Manual","page":1,"quote":"Dual AES50 SuperMAC ports for cascading"},"note":"AES50 SuperMAC (Klark Teknik)."},"phantom":{"value":"yes","unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL16_Manual","page":1,"quote":"MIDAS mic preamps ... switchable 48V phantom power"}},"connectors":{"value":"in/out: XLR; rete: 2× AES50 (etherCON)","unit_orig":"","reliability":"official","source":{"doc":"Midas_DL16_Manual","page":1,"quote":"Dual AES50 SuperMAC ports"}},"cascade":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL16_Manual","page":1,"quote":"cascading additional DL16 stageboxes - no merger or router required"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('midas-dl32', 'Midas', 'DL32', 'stagebox', 'current', 'midas-dl32-manual', $eq${"id":"midas-dl32","brand":"Midas","model":"DL32","category":"stagebox","inputs":{"value":32,"unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL32_Manual","page":1,"quote":"32 XLR mic/line inputs (remote-controllable preamps)"}},"outputs":{"value":16,"unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL32_Manual","page":1,"quote":"16 XLR line outputs"}},"protocol":{"value":"AES50","unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL32_Manual","page":1,"quote":"2 AES50 (SuperMAC, Cat5e, up to 100 m)"}},"phantom":{"value":"yes","unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL32_Manual","page":1,"quote":"32 MIDAS PRO Series remote-controllable mic preamps ... with switchable 48V phantom power"}},"connectors":{"value":"in/out: XLR; rete: 2× AES50 (Cat5e); +2 ADAT, 2 AES/EBU, ULTRANET","unit_orig":"","reliability":"official","source":{"doc":"Midas_DL32_Manual","page":1,"quote":"2 ADAT (TOSLINK) ... 2 AES/EBU (XLR) ... 1 ULTRANET (RJ45)"}},"cascade":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Midas_DL32_Manual","page":1,"quote":"Two DL32 Stage Boxes can be cascaded ... up to 64 mic/line inputs"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
commit;
