-- equip-seed-di.sql — 6 DI aggiuntivi (specifiche ufficiali produttore, ricerca web 18/07/2026)
-- Idempotente (upsert). Eseguire nel SQL editor Supabase DOPO la 0015 e il seed principale.
begin;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('bss-ar-133-productspec', 'BSS', 'AR-133', 'di', 'ProductSpec', 'en', 'https://bssaudio.com/en-US/products/ar-133', 'BSS_AR-133_ProductSpec.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('radial-prod2-specifications', 'Radial', 'ProD2', 'di', 'ProductSpec', 'en', 'https://www.radialeng.com/product/prod2/specifications', 'Radial_ProD2_Specifications.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('radial-prodi-specifications', 'Radial', 'ProDI', 'di', 'ProductSpec', 'en', 'https://www.radialeng.com/product/prodi/specifications', 'Radial_ProDI_Specifications.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('behringer-di100-productspec', 'Behringer', 'Ultra-DI DI100', 'di', 'ProductSpec', 'en', 'https://www.behringer.com/product.html?modelCode=0809-AAA', 'Behringer_DI100_ProductSpec.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('radial-jdi-duplex-smartsheet', 'Radial', 'JDI Duplex', 'di', 'ProductSpec', 'en', 'https://www.radialeng.com/product/jdi-duplex', 'Radial_JDI_Duplex_SmartSheet.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_document (id, brand, model_or_family, category, doc_type, language, official_url, filename, source_quality)
values ('whirlwind-imp2-productspec', 'Whirlwind', 'IMP 2', 'di', 'ProductSpec', 'en', 'https://www.whirlwindusa.com/products/black-boxes-effects-and-dis-direct-boxes-imp2', 'Whirlwind_IMP2_ProductSpec.pdf', 'web-manufacturer')
on conflict (id) do update set official_url=excluded.official_url, source_quality=excluded.source_quality;
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('bss-ar133', 'BSS', 'AR-133', 'di', 'current', 'bss-ar-133-productspec', $eq${"id":"bss-ar133","brand":"BSS","model":"AR-133","category":"di","active":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"BSS_AR-133_ProductSpec","page":1,"quote":"AR-133 Active DI Box"}},"channels":{"value":1,"unit_orig":null,"reliability":"official","source":{"doc":"BSS_AR-133_ProductSpec","page":1,"quote":"single channel DI box with high input impedance"},"note":"DI mono: 1 ingresso strumento + link parallelo, uscita XLR."},"phantom":{"value":"optional_battery","unit_orig":null,"reliability":"official","source":{"doc":"BSS_AR-133_ProductSpec","page":1,"quote":"accepts supply voltages of +48 volts down to +20 volts ... automatically switches over to the internal 9V battery"},"note":"Alimentazione phantom 20-48 V oppure batteria 9V con commutazione automatica."},"pad_db":{"value":[20,40],"unit_orig":"dB","reliability":"official","source":{"doc":"BSS_AR-133_ProductSpec","page":1,"quote":"Input attenuation is 0, -20 or -40dB"},"note":"Attenuazione 0/-20/-40 dB (strumento/linea/ampli)."},"groundLift":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"Ground lift presente sul prodotto ma non citato nella specifica recuperata."},"transformer":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"Uscita bilanciata; presenza trasformatore non citata nella specifica recuperata."},"connectors":{"value":"in: 1/4\" jack + XLR; thru: 1/4\" jack; out: XLR","unit_orig":"","reliability":"official","source":{"doc":"BSS_AR-133_ProductSpec","page":1,"quote":"Input connectors are both 1/4\" jack sockets and an XLR socket ... output ... via an XLR connector"}},"weight_g":{"value":650,"unit_orig":"g","reliability":"official","source":{"doc":"BSS_AR-133_ProductSpec","page":1,"quote":"Weight: 650gm excluding battery"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('radial-prod2', 'Radial', 'ProD2', 'di', 'current', 'radial-prod2-specifications', $eq${"id":"radial-prod2","brand":"Radial","model":"ProD2","category":"di","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"Audio circuit type: Passive, transformer based"}},"channels":{"value":2,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"2-channel passive direct box ... connect stereo keyboards"},"note":"DI stereo: 2 canali per sorgenti stereo (tastiere)."},"phantom":{"value":"no","unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"Power: Passive, no power required"}},"pad_db":{"value":[15],"unit_orig":"dB","reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"A -15 dB pad on each channel"}},"groundLift":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"the ground lift switches help eliminate hum and buzz"}},"transformer":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"transformer based with Eclipse ET-DB2 transformers at a 12:1 ratio"}},"impedance_input_ohm":{"value":140000,"unit_orig":"Ohm","reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"Input Impedance: 140k Ohms, unbalanced"}},"maxLevel_dbu":{"value":18,"unit_orig":"dB","reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"Maximum Input: +18dB @ 20Hz"}},"connectors":{"value":"in: 1/4\"; thru: 1/4\"; out: XLR","unit_orig":"","reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"Input Connectors: 1/4\"; Output Connectors: XLR, 1/4\" thru"}},"weight_g":{"value":540,"unit_orig":"g","reliability":"official","source":{"doc":"Radial_ProD2_Specifications","page":1,"quote":"Weight: .54kg (1.2lbs)"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('radial-prodi', 'Radial', 'ProDI', 'di', 'current', 'radial-prodi-specifications', $eq${"id":"radial-prodi","brand":"Radial","model":"ProDI","category":"di","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"Audio circuit type: Passive, transformer based with Eclipse ET-DB2, 12:1 ratio"}},"channels":{"value":1,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"1-channel Passive Instrument Direct Box"}},"phantom":{"value":"no","unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"The ProDI does not require any power and it will ignore the phantom power"}},"pad_db":{"value":[15],"unit_orig":"dB","reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"Input pad"},"note":"Pad d'ingresso per sorgenti hot; valore -15 dB come la serie Pro."},"groundLift":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"Ground lift"}},"transformer":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"transformer based with Eclipse ET-DB2, 12:1 ratio transformer"}},"impedance_input_ohm":{"value":140000,"unit_orig":"Ohm","reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"140kΩ input impedance"}},"maxLevel_dbu":{"value":18,"unit_orig":"dB","reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"Maximum Input: +18dB @ 20Hz"}},"connectors":{"value":"in: 1/4\" in & thru; out: XLR-M","unit_orig":"","reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"Input Connectors: 1/4\" in & thru, Output Connectors: XLR-M out"}},"weight_g":{"value":540,"unit_orig":"g","reliability":"official","source":{"doc":"Radial_ProDI_Specifications","page":1,"quote":"Weight: 1.2lb (0.54kg)"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('behringer-di100', 'Behringer', 'Ultra-DI DI100', 'di', 'current', 'behringer-di100-productspec', $eq${"id":"behringer-di100","brand":"Behringer","model":"Ultra-DI DI100","category":"di","active":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Behringer_DI100_ProductSpec","page":1,"quote":"1-channel Active Microphone / Instrument Direct Box"}},"channels":{"value":1,"unit_orig":null,"reliability":"official","source":{"doc":"Behringer_DI100_ProductSpec","page":1,"quote":"1-channel"}},"phantom":{"value":"optional_battery","unit_orig":null,"reliability":"official","source":{"doc":"Behringer_DI100_ProductSpec","page":1,"quote":"run off a 9V battery, or from +48V phantom power ... phantom power specification is 18 V DC to 48 V DC"},"note":"Phantom 18-48 V oppure batteria 9V (esclusione automatica con phantom)."},"pad_db":{"value":[20,40],"unit_orig":"dB","reliability":"official","source":{"doc":"Behringer_DI100_ProductSpec","page":1,"quote":"Switchable input attenuation ... Maximum Input Level: +10/+30/+50 dBu"},"note":"Attenuatore d'ingresso (max +10/+30/+50 dBu)."},"groundLift":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"Interruttore ground lift tipico del modello, non citato nella specifica recuperata."},"transformer":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"DI attiva; presenza trasformatore non citata."},"connectors":{"value":"in: 1/4\" + thru; out: XLR","unit_orig":"","reliability":"official","source":{"doc":"Behringer_DI100_ProductSpec","page":1,"quote":"direct connection to speaker outputs with up to 3,000 Watts"},"note":"Ingresso/thru 1/4\", uscita XLR bilanciata."},"weight_g":{"value":650,"unit_orig":"g","reliability":"official","source":{"doc":"Behringer_DI100_ProductSpec","page":1,"quote":"Weight: approximately 650 g"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('radial-jdi-duplex', 'Radial', 'JDI Duplex', 'di', 'current', 'radial-jdi-duplex-smartsheet', $eq${"id":"radial-jdi-duplex","brand":"Radial","model":"JDI Duplex","category":"di","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"The passive design requires no power"}},"channels":{"value":2,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"high performance 2-channel passive direct box"},"note":"DI stereo: 2 canali con trasformatori Jensen, funzione Merge."},"phantom":{"value":"no","unit_orig":null,"reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"The passive design requires no power, preventing ground loops and hum"}},"pad_db":{"value":[15],"unit_orig":"dB","reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"-15 dB pad"}},"groundLift":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"ground lift"}},"transformer":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"two world-class Jensen JT-DB-EPC audio transformers"}},"connectors":{"value":"in: 1/4\", RCA, 3.5mm TRS, XLR; out: XLR","unit_orig":"","reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"multiple input options (1/4\", RCA, 3.5mm TRS, XLR), -15 dB pad, merge function, and ground lift"}},"freqResp_lo_hz":{"value":10,"unit_orig":"Hz","reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"Ruler flat from 10Hz to 40kHz"}},"freqResp_hi_hz":{"value":40000,"unit_orig":"Hz","reliability":"official","source":{"doc":"Radial_JDI_Duplex_SmartSheet","page":1,"quote":"Ruler flat from 10Hz to 40kHz"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
insert into equip_product (id, brand, model, category, commercial_status, primary_source_doc, data)
values ('whirlwind-imp2', 'Whirlwind', 'IMP 2', 'di', 'current', 'whirlwind-imp2-productspec', $eq${"id":"whirlwind-imp2","brand":"Whirlwind","model":"IMP 2","category":"di","active":{"value":false,"unit_orig":null,"reliability":"official","source":{"doc":"Whirlwind_IMP2_ProductSpec","page":1,"quote":"Passive Direct Box"}},"channels":{"value":1,"unit_orig":null,"reliability":"official","source":{"doc":"Whirlwind_IMP2_ProductSpec","page":1,"quote":"1-channel Passive Instrument Direct Box"}},"phantom":{"value":"no","unit_orig":null,"reliability":"official","source":{"doc":"Whirlwind_IMP2_ProductSpec","page":1,"quote":"passive direct box"},"note":"Passiva: nessuna alimentazione."},"pad_db":{"value":null,"unit_orig":null,"reliability":"official","source":null,"note":"Nessun pad commutabile; riduzione fissa -20 dB dal trasformatore 133:1."},"groundLift":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Whirlwind_IMP2_ProductSpec","page":1,"quote":"a Ground Lift switch to help isolate hum and buzz"}},"transformer":{"value":true,"unit_orig":null,"reliability":"official","source":{"doc":"Whirlwind_IMP2_ProductSpec","page":1,"quote":"uses Whirlwind's TRHL transformer ... riveted, not glued"},"note":"Rapporto 133:1."},"connectors":{"value":"in/out: 1/4\" parallel; out: XLR","unit_orig":"","reliability":"official","source":{"doc":"Whirlwind_IMP2_ProductSpec","page":1,"quote":"1/4\" parallel wired in/out jacks"},"note":"Ingresso Hi-Z, uscita mic-level bilanciata XLR."},"maxLevel_dbu":{"value":-20,"unit_orig":"dB","reliability":"official","source":{"doc":"Whirlwind_IMP2_ProductSpec","page":1,"quote":"Level Change (input to output): -20dB"}}}$eq$::jsonb)
on conflict (id) do update set data=excluded.data, updated_at=now();
commit;
